In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("Dataset for Data Analytics.xlsx")

In [ ]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

In [ ]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [ ]:
df["CouponCode"] = df["CouponCode"].fillna("No Coupon")
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["OrderID"].duplicated().sum()

np.int64(0)

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])

In [ ]:
df["Date"] = df["Date"].dt.strftime("%Y-%m-%d")

In [ ]:
df["Product"] = df["Product"].str.title().str.strip()

df["PaymentMethod"] = df["PaymentMethod"].str.title().str.strip()

df["ReferralSource"] = df["ReferralSource"].str.title().str.strip()

df["OrderStatus"] = df["OrderStatus"].str.title().str.strip()

In [ ]:
df["UnitPrice"] = df["UnitPrice"].round(2)

df["TotalPrice"] = df["TotalPrice"].round(2)

df["CalculatedTotal"] = (df["Quantity"] * df["UnitPrice"]).round(2)

In [ ]:
df[["Quantity", "UnitPrice", "TotalPrice", "CalculatedTotal"]].head()

   Quantity  UnitPrice  TotalPrice  CalculatedTotal
0         5     570.62     2853.10          2853.10
1         2     151.35      302.70           302.70
2         5     550.68     2753.40          2753.40
3         1     273.19      273.19           273.19
4         4     626.01     2504.04          2504.04

In [ ]:
incorrect_totals = df[df["TotalPrice"] != df["CalculatedTotal"]]

incorrect_totals.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice,CalculatedTotal
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40,2753.40
10,ORD200010,2023-12-29,C43443,Tablet,5,625.97,333 Main St,Credit Card,Returned,TRK98859248,9,WINTER15,Instagram,3129.85,3129.85
11,ORD200011,2024-02-17,C93861,Monitor,3,49.14,831 Main St,Online,Returned,TRK48234646,7,SAVE10,Email,147.42,147.42
32,ORD200032,2023-05-01,C12388,Tablet,5,536.72,830 Main St,Cash,Delivered,TRK99261395,10,No Coupon,Email,2683.60,2683.60
39,ORD200039,2025-02-27,C96664,Printer,3,256.46,666 Main St,Credit Card,Delivered,TRK85508960,4,SAVE10,Referral,769.38,769.38

In [ ]:
df.loc[df["TotalPrice"] != df["CalculatedTotal"], "TotalPrice"] = df["CalculatedTotal"]

In [ ]:
incorrect_totals = df[df["TotalPrice"] != df["CalculatedTotal"]]

incorrect_totals.head()

Empty DataFrame
Columns: [OrderID, Date, CustomerID, Product, Quantity, UnitPrice, ShippingAddress, PaymentMethod, OrderStatus, TrackingNumber, ItemsInCart, CouponCode, ReferralSource, TotalPrice, CalculatedTotal]
Index: []

In [ ]:
df["TotalPrice"] = df["CalculatedTotal"]

In [ ]:
print(df.isnull().sum())

print(df.duplicated().sum())

print(df["OrderID"].duplicated().sum())

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
CalculatedTotal    0
dtype: int64
0
0

In [ ]:
df.to_excel("cleaned_dataset_for_data_analytics.xlsx", index=False)